#!/bin/bash

thinkfan="/etc/thinkfan.conf"
dev=$(find /sys/devices -type f -name "temp*_input"|grep coretemp|sed 's/^/hwmon /g')

echo "$dev" > $thinkfan

printf "
tp_fan /proc/acpi/ibm/fan

(0, 0 , 39)
(1, 39, 52)
(2, 51, 55)
(3, 54, 58)
(4, 56, 66)
(5, 64, 70)
(6, 68, 80)
(7, 79, 86)
(127, 84, 32767)" >> $thinkfan

# devconf = device temperature and fan speed configs for ThinkFan, respectively
printf "thinkfan is configured for %d devices.\n" "$(echo \""$dev\""|wc -l)"
